
name: randomator-staging
docker:
  auth_secret_name: docker-auth

deployments:
  front:
    replicas: 1
    image: barnabepilliaudin/randomator:front-latest
    container_port: 80
    env:
      VITE_API_URL: http://staging-back.barnabepilliaudin.fr
  back:
    replicas: 1
    image: barnabepilliaudin/randomator:back-latest
    container_port: 3000
    env:
      CORS: http://staging-front.barnabepilliaudin.fr

services:
  front:
    external_port: 80
    type: ClusterIP
  back:
    external_port: 3000
    type: ClusterIP

ingresses:
  front:
    domain: staging-front.barnabepilliaudin.fr
    tls: true
    tls_secret: front-tls-secret
  back:
    domain: staging-back.barnabepilliaudin.fr
    tls: true
    tls_secret: back-tls-secret
